### PR TITLE
dx describe file for MokaWes1.6

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7)

### CODE REVIEW

**Comment by aledj2** [comment]
can we remove the ingenuity import? if there i a rush for this then we can remove it from v1.7

**Comment by natashapinto** [comment]
Oh yes, thanks for the reminder. I'll do that now!

**Review by andyb3 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[MokaWES.txt, line 11 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7#-LqaPw6_8aDHgJptSFkL:-LqaPw6_8aDHgJptSFkM:b4d9j56) ([raw file](https://github.com/moka-guys/dnanexus_mokawes_workflow/blob/6c3effef7d91abf22fa96d6c825a9507e5acc03c/MokaWES.txt#L11)):*
> ```
> Types               -
> Properties          -
> Tags                -
> ```

Please could you add the github release property and the WES tag in DNAnexus? I can show you how to do this.
___
*[MokaWes16.txt, line 1 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7#-LqaQLcq2tuV41DSTmov:-LqaQLcq2tuV41DSTmow:b-7aopn3) ([raw file](https://github.com/moka-guys/dnanexus_mokawes_workflow/blob/6c3effef7d91abf22fa96d6c825a9507e5acc03c/MokaWes16.txt#L1)):*
> ```
> Result 1:
> ```

Can you remove this file with git rm, then commit and push to the branch?

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andyb3)

___
*[MokaWES.txt, line 11 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7#-LqaPw6_8aDHgJptSFkL:-LqaYSRt3-9oPAsWvIym:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokawes_workflow/blob/6c3effef7d91abf22fa96d6c825a9507e5acc03c/MokaWES.txt#L11)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Please could you add the github release property and the WES tag in DNAnexus? I can show you how to do this.
</blockquote></details>

Done.
___
*[MokaWes16.txt, line 1 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7#-LqaQLcq2tuV41DSTmov:-LqaYUFlCJFxOQz7UuKm:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokawes_workflow/blob/6c3effef7d91abf22fa96d6c825a9507e5acc03c/MokaWes16.txt#L1)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Can you remove this file with git rm, then commit and push to the branch?
</blockquote></details>

Done.

**Review by andyb3 — CHANGES_REQUESTED** [review]
+@andyb3 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7#-:-LqaYoJV4UdY5M8-10Va:bxccsfn)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[MokaWES.txt, line 10 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7#-LqaZjZc538JiYrtn97z:-LqaZjZc538JiYrtn98-:bhh7e1c) ([raw file](https://github.com/moka-guys/dnanexus_mokawes_workflow/blob/6ab3d3dd0823f86de4c90aee4b2e205cdf360bc9/MokaWES.txt#L10)):*
> ```
> Visibility          visible
> Types               -
> Properties          github release=1.6
> ```

sorry, just noticed we usually put a 'v' at the front, so could you change this to v1.6? (Sorry!)

**Review by andyb3 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[MokaWES.txt, line 10 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_mokawes_workflow/7#-LqaZjZc538JiYrtn97z:-LqaeTS14tGXSCOLcoxf:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokawes_workflow/blob/6ab3d3dd0823f86de4c90aee4b2e205cdf360bc9/MokaWES.txt#L10)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

sorry, just noticed we usually put a 'v' at the front, so could you change this to v1.6? (Sorry!)
</blockquote></details>

Done.

**Pull request merged**
